# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build the keyboard'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["the_keyboard_left", "the_keyboard_right"]'
      alphas: '["QWERTY"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["urob/zmk/mouse-3.2"]'
